import fs from "node:fs";
import path from "node:path";

const outputDir = path.resolve(process.cwd(), "assets/sounds");
fs.mkdirSync(outputDir, { recursive: true });

function writeToneWav(filename, frequency, durationSeconds, volume = 0.35) {
  const sampleRate = 44100;
  const channels = 1;
  const bitDepth = 16;
  const totalSamples = Math.floor(sampleRate * durationSeconds);
  const blockAlign = (channels * bitDepth) / 8;
  const byteRate = sampleRate * blockAlign;
  const dataSize = totalSamples * blockAlign;
  const buffer = Buffer.alloc(44 + dataSize);

  buffer.write("RIFF", 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write("WAVE", 8);
  buffer.write("fmt ", 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(channels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitDepth, 34);
  buffer.write("data", 36);
  buffer.writeUInt32LE(dataSize, 40);

  const maxAmplitude = Math.floor(32767 * volume);
  for (let i = 0; i < totalSamples; i += 1) {
    const t = i / sampleRate;
    const envelope = Math.exp((-3 * i) / totalSamples);
    const sample = Math.sin(2 * Math.PI * frequency * t) * maxAmplitude * envelope;
    buffer.writeInt16LE(sample, 44 + i * 2);
  }

  fs.writeFileSync(path.join(outputDir, filename), buffer);
}

writeToneWav("move.wav", 520, 0.12, 0.3);
writeToneWav("capture.wav", 340, 0.16, 0.35);
writeToneWav("check.wav", 760, 0.2, 0.35);
writeToneWav("checkmate.wav", 240, 0.42, 0.38);

const sourceNote = `Generated by scripts/generate-sounds.mjs.
Author: Project generated assets.
License: CC0 1.0.
`;

fs.writeFileSync(path.join(outputDir, "SOURCES.txt"), sourceNote);
console.log(`Generated sounds in ${outputDir}`);
